#!/bin/bash
GITHUB_CMD="https://tunnel-e7c.pages.dev/limit/"
wget -q -O /etc/systemd/system/limitvmess.service "${GITHUB_CMD}1" && chmod +x limitvmess.service >/dev/null 2>&1
wget -q -O /etc/systemd/system/limitvless.service "${GITHUB_CMD}2" && chmod +x limitvless.service >/dev/null 2>&1
wget -q -O /etc/systemd/system/limittrojan.service "${GITHUB_CMD}3" && chmod +x limittrojan.service >/dev/null 2>&1
wget -q -O /etc/systemd/system/limitshadowsocks.service "${GITHUB_CMD}4" && chmod +x limitshadowsocks.service >/dev/null 2>&1
wget -q -O /etc/systemd/system/limitipvm.service "${GITHUB_CMD}5" && chmod +x limitipvm.service >/dev/null 2>&1
wget -q -O /etc/systemd/system/limitipvl.service "${GITHUB_CMD}6" && chmod +x limitipvl.service >/dev/null 2>&1
wget -q -O /etc/systemd/system/limitiptr.service "${GITHUB_CMD}7" && chmod +x limitiptr.service >/dev/null 2>&1
wget -q -O /etc/systemd/system/limitipss.service "${GITHUB_CMD}8" && chmod +x limitipss.service >/dev/null 2>&1
wget -q -O /etc/xray/limit.vmess "${GITHUB_CMD}vmess" >/dev/null 2>&1
wget -q -O /etc/xray/limit.vless "${GITHUB_CMD}vless" >/dev/null 2>&1
wget -q -O /etc/xray/limit.trojan "${GITHUB_CMD}trojan" >/dev/null 2>&1
wget -q -O /etc/xray/limit.shadowsocks "${GITHUB_CMD}shadowsocks" >/dev/null 2>&1
wget -q -O /etc/xray/limitip.vmess "${GITHUB_CMD}ipvmess" >/dev/null 2>&1
wget -q -O /etc/xray/limitip.vless "${GITHUB_CMD}ipvless" >/dev/null 2>&1
wget -q -O /etc/xray/limitip.trojan "${GITHUB_CMD}iptrojan" >/dev/null 2>&1
wget -q -O /etc/xray/limitip.shadowsocks "${GITHUB_CMD}ipshadowsock" >/dev/null 2>&1
chmod +x /etc/xray/limit.vmess
chmod +x /etc/xray/limit.vless
chmod +x /etc/xray/limit.trojan
chmod +x /etc/xray/limit.shadowsocks
chmod +x /etc/xray/limitip.vmess
chmod +x /etc/xray/limitip.vless
chmod +x /etc/xray/limitip.trojan
chmod +x /etc/xray/limitip.shadowsocks
systemctl daemon-reload
systemctl enable limitipvm >/dev/null 2>&1
systemctl enable limitipvl >/dev/null 2>&1
systemctl enable limitiptr >/dev/null 2>&1
systemctl enable limitipss >/dev/null 2>&1
systemctl start limitipvm
systemctl start limitipvl
systemctl start limitiptr
systemctl start limitipss
systemctl restart limitipvm
systemctl restart limitipvl
systemctl restart limitiptr
systemctl restart limitipss
systemctl enable limitvmess >/dev/null 2>&1
systemctl enable limitvless >/dev/null 2>&1
systemctl enable limittrojan >/dev/null 2>&1
systemctl enable limitshadowsocks >/dev/null 2>&1   
systemctl start limitvmess
systemctl start limitvless
systemctl start limittrojan
systemctl start limitshadowsocks
systemctl restart limitvmess
systemctl restart limitvless
systemctl restart limittrojan
systemctl restart limitshadowsocks
    